/*----------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2, or (at your option) any 
later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than 
Coco/R itself) does not fall under the GNU General Public License.
-----------------------------------------------------------------------*/


module at.jku.ssw.coco {



/// <reference path="Scanner.ts" />

export class Parser {
	public static _EOF : number = 0;
	public static _ident : number = 1;
	public static _number : number = 2;
	public static _string : number = 3;
	public static _badString : number = 4;
	public static _char : number = 5;
	public static maxT : number = 41;
	public static _ddtSym : number = 42;
	public static _optionSym : number = 43;

	static T : bool = true;
	static x : bool = false;
	static minErrDist : number = 2;
	
	public scanner : Scanner;
	public errors : Errors;

	public t : Token;    // last recognized token
	public la : Token;   // lookahead token
	public errDist = Parser.minErrDist;

get id() : number { return 0; }
	get str() : number { return 1; }
	
	public trace : TextWriter ;    // other Coco objects referenced in this ATG
	public tab : Tab;
	public dfa : DFA;
	public pgen : ParserGen;

	genScanner : bool;
	tokenString : string;         // used in declarations of literal tokens
	noString : string = "-none-"; // used in declarations of literal tokens

/*-------------------------------------------------------------------------*/



	constructor(scanner : Scanner) 
	{
		this.scanner = scanner;
		this.errors = new Errors();
	}

	SynErr (n : number)
	{
		if (this.errDist >= Parser.minErrDist)
		{
			this.errors.SynErrPositioned(this.la.line, this.la.col, n);
		}

		this.errDist = 0;
	}

	SemErr (msg : string)
	{
		if (this.errDist >= Parser.minErrDist)
		{
			this.errors.SemErrPositioned(this.t.line, this.t.col, msg);
		}

		this.errDist = 0;
	}
	
	Get ()
	{
		for (;;)
		{
			this.t = this.la;
			this.la = this.scanner.Scan();
			if (this.la.kind <= Parser.maxT) 
			{ 
				this.errDist++; 
				break; 
			}
				if (this.la.kind == 42) {
				this.tab.SetDDT(this.la.val); 
				}
				if (this.la.kind == 43) {
				this.tab.SetOption(this.la.val); 
				}

			this.la = this.t;
		}
	}
	
	Expect (n : number) {
		if (this.la.kind == n)
		{
			this.Get(); 
		}
		else
		{ 
			this.SynErr(n);
		}
	}
	
	StartOf (s : number) : bool {
		return Parser.stateset[s][this.la.kind];
	}
	
	ExpectWeak (n : number, follow : number) {
		if (this.la.kind == n) this.Get();
		else {
			this.SynErr(n);
			while (!this.StartOf(follow)) this.Get();
		}
	}


	WeakSeparator(n : number, syFol : number, repFol : number) : bool {
		var kind = this.la.kind;
		if (kind == n) {this.Get(); return true;}
		else if (this.StartOf(repFol)) {return false;}
		else {
			this.SynErr(n);
			while (!(Parser.stateset[syFol, kind] || Parser.stateset[repFol, kind] || Parser.stateset[0, kind])) {
				this.Get();
				kind = this.la.kind;
			}
			return this.StartOf(syFol);
		}
	}

	
	Coco(ret : {}) {
		var sym : Symbol; var g : Graph; var g1 : Graph; var g2 : Graph; var gramName : string; var s : CharSet; var beg : number;var line : number; 
		if (this.StartOf(1)) {
			this.Get();
			beg = this.t.pos; line = this.t.line; 
			while (this.StartOf(1)) {
				this.Get();
			}
			this.pgen.usingPos = new Position(beg, this.la.pos, 0, line); 
		}
		this.Expect(6);
		genScanner = true; 
		this.tab.ignored = new CharSet(); 
		this.Expect(1);
		gramName = this.t.val;
		beg = this.la.pos; line = this.la.line;
		
		while (this.StartOf(2)) {
			this.Get();
		}
		this.tab.semDeclPos = new Position(beg, this.la.pos, 0, line); 
		if (this.la.kind == 7) {
			this.Get();
			this.dfa.ignoreCase = true; 
		}
		if (this.la.kind == 8) {
			this.Get();
			while (this.la.kind == 1) {
				this.SetDecl();
			}
		}
		if (this.la.kind == 9) {
			this.Get();
			while (this.la.kind == 1 || this.la.kind == 3 || this.la.kind == 5) {
				this.TokenDecl(Node.t);
			}
		}
		if (this.la.kind == 10) {
			this.Get();
			while (this.la.kind == 1 || this.la.kind == 3 || this.la.kind == 5) {
				this.TokenDecl(Node.pr);
			}
		}
		while (this.la.kind == 11) {
			this.Get();
			var nested = false; 
			this.Expect(12);
			this.TokenExpr(tokenexprg1);
			g1 = tokenexprg1.g; 
			this.Expect(13);
			this.TokenExpr(tokenexprg2);
			g2 = tokenexprg2.g; 
			if (this.la.kind == 14) {
				this.Get();
				nested = true; 
			}
			this.dfa.NewComment(g1.l, g2.l, nested); 
		}
		while (this.la.kind == 15) {
			this.Get();
			this.Set(sets);
			s = sets.s; this.tab.ignored.Or(s); 
		}
		while (!(this.la.kind == 0 || this.la.kind == 16)) {this.SynErr(42); Get();}
		this.Expect(16);
		if (genScanner) this.dfa.MakeDeterministic();
		this.tab.DeleteNodes();
		
		while (this.la.kind == 1) {
			this.Get();
			sym = this.tab.FindSym(t.val);
			var undef = sym == null;
			if (undef) sym = this.tab.NewSym(Node.nt, t.val, t.line);
			else {
			 if (sym.typ == Node.nt) {
			   if (sym.graph != null) this.SemErr("name declared twice");
			 } else { 
			   this.SemErr("this symbol kind not allowed on left side of production");
			 }
			 sym.line = t.line;
			}
			var noAttrs : bool = sym.attrPos == null;
			sym.attrPos = null;
			
			if (this.la.kind == 24 || this.la.kind == 26) {
				this.AttrDecl(sym);
			}
			if (!undef) {
			 if (noAttrs != (sym.attrPos == null)) {
			   this.SemErr("attribute mismatch between declaration and use of this symbol");
			 }
			}
			
			if (this.la.kind == 39) {
				this.SemText(out sym.semPos);
			}
			this.ExpectWeak(17, 3);
			this.Expression(out g);
			sym.graph = g.l;
			this.tab.Finish(g);
			
			this.ExpectWeak(18, 4);
		}
		this.Expect(19);
		this.Expect(1);
		if (gramName != this.t.val) {
		 this.SemErr("name does not match grammar name");
		 this.tab.gramSy = this.tab.FindSym(gramName);
		}
		if (this.tab.gramSy == null) {
		 this.SemErr("missing production for grammar name");
		} else {
		 sym = this.tab.gramSy;
		 if (sym.attrPos != null) {
		   this.SemErr("grammar symbol must not have attributes");
		 }
		}
		this.tab.noSym = this.tab.NewSym(Node.t, "???", 0); // noSym gets highest number
		this.tab.SetupAnys();
		this.tab.RenumberPragmas();
		if (this.tab.ddt[2]) {
		  this.tab.PrintNodes();
		}
		if (errors.count == 0) {
		 Console.WriteLine("checking");
		 this.tab.CompSymbolSets();
		 if (this.tab.ddt[7]) { this.tab.XRef(); }
		 if (this.tab.GrammarOk()) {
		   Console.Write("parser");
		   this.pgen.WriteParser();
		   if (genScanner) {
		     Console.Write(" + scanner");
		     this.dfa.WriteScanner();
		     if (this.tab.ddt[0]) { this.dfa.PrintStates(); }
		   }
		   Console.WriteLine(" generated");
		   if (this.tab.ddt[8]) { pgen.WriteStatistics(); }
		 }
		}
		if (this.tab.ddt[6]) { this.tab.PrintSymbolTable(); }
		
		this.Expect(18);
	}
	SetDecl(ret : {}) {
		var s : CharSet; 
		this.Expect(1);
		var name = t.val;
		var c = this.tab.FindCharClass(name);
		if (c != null) { this.SemErr("name declared twice"); }
		
		this.Expect(17);
		this.Set(s);
		if (s.Elements() == 0) { this.SemErr("character set must not be empty"); }
		this.tab.NewCharClass(name, s);
		
		this.Expect(18);
	}
	TokenDecl(ret : {typ : number}) {
		var name : string; var kind : number; var sym : Symbol; var g : Graph; 
		this.Sym(name, kind);
		sym = this.tab.FindSym(name);
		if (sym != null) { this.SemErr("name declared twice"); }
		else {
		 sym = this.tab.NewSym(typ, name, t.line);
		 sym.tokenKind = Symbol.fixedToken;
		}
		tokenString = null;
		
		while (!(this.StartOf(5))) {this.SynErr(43); Get();}
		if (this.la.kind == 17) {
			this.Get();
			this.TokenExpr(g);
			this.Expect(18);
			if (kind == str) { this.SemErr("a literal must not be declared with a structure"); }
			this.tab.Finish(g);
			if (tokenString == null || tokenString.Equals(noString)) {
			 this.dfa.ConvertToStates(g.l, sym);
			} else { // TokenExpr is a single string
			 if (this.tab.literals[tokenString] != null) {
			   this.SemErr("token string declared twice");
			 }
			 this.tab.literals[tokenString] = sym;
			 this.dfa.MatchLiteral(tokenString, sym);
			}
			
		} else if (this.StartOf(6)) {
			if (kind == id) { genScanner = false; }
			else { this.dfa.MatchLiteral(sym.name, sym); }
			
		} else this.SynErr(44);
		if (this.la.kind == 39) {
			this.SemText(out sym.semPos);
			if (typ != Node.pr) { this.SemErr("semantic action not allowed here"); } 
		}
	}
	TokenExpr(ret : {g : Graph;}) {
		var g2 : Graph; 
		this.TokenTerm(tokentermg);
		ret.g = tokentermg.g; var first = true; 
		while (this.WeakSeparator(28,7,8) ) {
			this.TokenTerm(tokentermg2);
			g2 = tokentermg2.g;
			if (first) { this.tab.MakeFirstAlt(ret.g); first = false; }
			this.tab.MakeAlternative(ret.g, g2);
			
		}
	}
	Set(ret : {s : CharSet;}) {
		var s2 : CharSet; 
		this.SimSet(ret.s);
		while (this.la.kind == 20 || this.la.kind == 21) {
			if (this.la.kind == 20) {
				this.Get();
				this.SimSet(s2);
				ret.s.Or(s2); 
			} else {
				this.Get();
				this.SimSet(s2);
				ret.s.Subtract(s2); 
			}
		}
	}
	AttrDecl(ret : {sym : Symbol;}) {
		if (this.la.kind == 24) {
			this.Get();
			var beg = this.la.pos; var col = this.la.col; var line = this.la.line; 
			while (this.StartOf(9)) {
				if (this.StartOf(10)) {
					this.Get();
				} else {
					this.Get();
					this.SemErr("bad string in attributes"); 
				}
			}
			this.Expect(25);
			if (t.pos > beg) {
			 sym.attrPos = new Position(beg, t.pos, col, line); 
			} 
			
		} else if (this.la.kind == 26) {
			this.Get();
			var beg = this.la.pos; var col = this.la.col; var line = this.la.line; 
			while (this.StartOf(11)) {
				if (this.StartOf(12)) {
					this.Get();
				} else {
					this.Get();
					this.SemErr("bad string in attributes"); 
				}
			}
			this.Expect(27);
			if (t.pos > beg) {
			 sym.attrPos = new Position(beg, t.pos, col, line); 
			} 
			
		} else this.SynErr(45);
	}
	SemText(ret : {pos : Position;}) {
		this.Expect(39);
		var beg = this.la.pos; var col = this.la.col; var line = this.la.line; 
		while (this.StartOf(13)) {
			if (this.StartOf(14)) {
				this.Get();
			} else if (this.la.kind == 4) {
				this.Get();
				this.SemErr("bad string in semantic action"); 
			} else {
				this.Get();
				this.SemErr("missing end of previous semantic action"); 
			}
		}
		this.Expect(40);
		ret.pos = new Position(beg, t.pos, col, line); 
	}
	Expression(ret : {g : Graph;}) {
		this.Term(term1);
		ret.g = term1.g; var first = true; 
		while (this.WeakSeparator(28,15,16) ) {
			this.Term(term2);
			if (first) { this.tab.MakeFirstAlt(ret.g); first = false; }
			this.tab.MakeAlternative(ret.g, term2.g);
			
		}
	}
	SimSet(ret : {s : CharSet;}) {
		var n1 : number; var n2 : number; 
		s = new CharSet(); 
		if (this.la.kind == 1) {
			this.Get();
			var c = this.tab.FindCharClass(t.val);
			if (c == null) { this.SemErr("undefined name"); } else { s.Or(c.set); }
			
		} else if (this.la.kind == 3) {
			this.Get();
			var name = t.val;
			name = this.tab.Unescape(name.Substring(1, name.Length-2));
			foreach (char ch in name) {
			 if (this.dfa.ignoreCase) { s.Set(char.ToLower(ch)); }
			 else { s.Set(ch); }
			}  
		} else if (this.la.kind == 5) {
			this.Char(n1 : number;);
			s.Set(n1); 
			if (this.la.kind == 22) {
				this.Get();
				this.Char(n2);
				for (var i = n1; i <= n2; i++) { s.Set(i); } 
			}
		} else if (this.la.kind == 23) {
			this.Get();
			s = new CharSet(); s.Fill(); 
		} else this.SynErr(46);
	}
	Char(ret : {n : string;}) {
		this.Expect(5);
		var name = t.val; n = '\0';
		name = this.tab.Unescape(name.Substring(1, name.Length-2));
		if (name.Length == 1) { n = name[0]; }
		else { this.SemErr("unacceptable character value"); }
		if (this.dfa.ignoreCase && n >= 'A' && n <= 'Z') n = n.toUpper();
		
	}
	Sym(ret : {name : string; kind : number;}) {
		ret.name = "???"; ret.kind = id; 
		if (this.la.kind == 1) {
			this.Get();
			ret.kind = id; ret.name = t.val; 
		} else if (this.la.kind == 3 || this.la.kind == 5) {
			if (this.la.kind == 3) {
				this.Get();
				ret.name = t.val; 
			} else {
				this.Get();
				ret.name = "\"" + t.val.Substring(1, t.val.Length-2) + "\""; 
			}
			ret.kind = str;
			if (this.dfa.ignoreCase) ret.name = ret.name.ToLower();
			if (ret.name.IndexOf(' ') >= 0)
			 this.SemErr("literal tokens must not contain blanks"); 
		} else this.SynErr(47);
	}
	Term(ret : {g : Graph;}) {
		var g2 : Graph; var rslv : Node = null; g = null; 
		if (this.StartOf(17)) {
			if (this.la.kind == 37) {
				rslv = this.tab.NewNode(Node.rslv, null, this.la.line); 
				this.Resolver(rslvpos);
				rslv.pos = rslvpos.pos; g = new Graph(rslv); 
			}
			this.Factor(factorg2);
			g2 = factorg2.g;
			if (rslv != null) this.tab.MakeSequence(ret.g, ret.g2);
			else ret.g = g2;
			
			while (this.StartOf(18)) {
				this.Factor(factorg2);
				g2 = factorg2.g; this.tab.MakeSequence(ret.g, ret.g2); 
			}
		} else if (this.StartOf(19)) {
			g = new Graph(this.tab.NewNode(Node.eps, null, 0)); 
		} else this.SynErr(48);
		if (g == null) { // invalid start of Term
		 g = new Graph(this.tab.NewNode(Node.eps, null, 0));
		}
		
	}
	Resolver(ret : {pos : Position;}) {
		this.Expect(37);
		this.Expect(30);
		var beg = this.la.pos; var col = this.la.col; var line = this.la.line; 
		this.Condition();
		ret.pos = new Position(beg, t.pos, col, line); 
	}
	Factor(ret : {out Graph g}) {
		var name : string; var kind : number; var pos : Position; var weak : bool = false; 
		g = null;
		
		switch (this.la.kind) {
		case 1: case 3: case 5: case 29: {
			if (this.la.kind == 29) {
				this.Get();
				weak = true; 
			}
			this.Sym(out name, out kind);
			var sym = this.tab.FindSym(name);
			if (sym == null && kind == str)
			 sym = this.tab.literals[name] as Symbol;
			var undef = sym == null;
			if (undef) {
			 if (kind == id) {
			   sym = this.tab.NewSym(Node.nt, name, 0);  // forward nt
			 } else if (genScanner) { 
			   sym = this.tab.NewSym(Node.t, name, t.line);
			   this.dfa.MatchLiteral(sym.name, sym);
			 } else {  // undefined string in production
			   this.SemErr("undefined string in production");
			   sym = this.tab.eofSy;  // dummy
			 }
			}
			var typ = sym.typ;
			if (typ != Node.t && typ != Node.nt) {
			 this.SemErr("this symbol kind is not allowed in a production");
			}
			if (weak) {
			 if (typ == Node.t) { typ = Node.wt; }
			 else { this.SemErr("only terminals may be weak"); }
			}
			var p = this.tab.NewNode(typ, sym, t.line);
			g = new Graph(p);
			
			if (this.la.kind == 24 || this.la.kind == 26) {
				this.Attribs(p);
				if (kind != id) { this.SemErr("a literal must not have attributes"); } 
			}
			if (undef) {
			 sym.attrPos = p.pos;  // dummy
			} else if ((p.pos == null) != (sym.attrPos == null)) {
			 this.SemErr("attribute mismatch between declaration and use of this symbol");
			}
			
			break;
		}
		case 30: {
			this.Get();
			this.Expression(out g);
			this.Expect(31);
			break;
		}
		case 32: {
			this.Get();
			this.Expression(out g);
			this.Expect(33);
			this.tab.MakeOption(g); 
			break;
		}
		case 34: {
			this.Get();
			this.Expression(out g);
			this.Expect(35);
			this.tab.MakeIteration(g); 
			break;
		}
		case 39: {
			this.SemText(out pos);
			Node p = this.tab.NewNode(Node.sem, null, 0);
			p.pos = pos;
			g = new Graph(p);
			
			break;
		}
		case 23: {
			this.Get();
			var p = this.tab.NewNode(Node.any, null, 0);  // p.set is set in this.tab.SetupAnys
			g = new Graph(p);
			
			break;
		}
		case 36: {
			this.Get();
			var p = this.tab.NewNode(Node.sync, null, 0);
			g = new Graph(p);
			
			break;
		}
		default: this.SynErr(49); break;
		}
		if (g == null) {// invalid start of Factor
		 g = new Graph(this.tab.NewNode(Node.eps, null, 0));
		}
	}
	Attribs(ret : {p : Node}) {
		if (this.la.kind == 24) {
			this.Get();
			var beg = this.la.pos; var col = this.la.col; var line = this.la.line; 
			while (this.StartOf(9)) {
				if (this.StartOf(10)) {
					this.Get();
				} else {
					this.Get();
					this.SemErr("bad string in attributes"); 
				}
			}
			this.Expect(25);
			if (t.pos > beg) p.pos = new Position(beg, t.pos, col, line); 
		} else if (this.la.kind == 26) {
			this.Get();
			var beg = this.la.pos; var col = this.la.col; var line = this.la.line; 
			while (this.StartOf(11)) {
				if (this.StartOf(12)) {
					this.Get();
				} else {
					this.Get();
					this.SemErr("bad string in attributes"); 
				}
			}
			this.Expect(27);
			if (t.pos > beg) p.pos = new Position(beg, t.pos, col, line); 
		} else this.SynErr(50);
	}
	Condition(ret : {}) {
		while (this.StartOf(20)) {
			if (this.la.kind == 30) {
				this.Get();
				this.Condition();
			} else {
				this.Get();
			}
		}
		this.Expect(31);
	}
	TokenTerm(ret : {g: Graph;}) {
		var g2 : Graph; 
		this.TokenFactor(tokenfactorg);
		g = tokenfactorg.g; 
		while (this.StartOf(7)) {
			this.TokenFactor(tokenfactorg2);
			g2 = tokenfactorg2.g; 
			this.tab.MakeSequence(g, g2); 
		}
		if (this.la.kind == 38) {
			this.Get();
			this.Expect(30);
			this.TokenExpr(tokenexprg2);
			g2 = tokenexprg2.g; 
			this.tab.SetContextTrans(g2.l); this.dfa.hasCtxMoves = true;
			this.tab.MakeSequence(g, g2); 
			this.Expect(31);
		}
	}
	TokenFactor(ret : {g : Graph;}) {
		
		ret.g = null; 
		if (this.la.kind == 1 || this.la.kind == 3 || this.la.kind == 5) {
			this.Sym(sym);
			if (sym.kind == id) {
			 var c = this.tab.FindCharClass(sym.name);
			 if (c == null) {
			   this.SemErr("undefined name");
			   c = this.tab.NewCharClass(sym.name, new CharSet());
			 }
			 var p = this.tab.NewNode(Node.clas, null, 0); 
			 p.val = c.n;
			 ret.g = new Graph(p);
			 tokenString = noString;
			} else { // str
			 ret.g = this.tab.StrToGraph(sym.name);
			 if (tokenString == null) tokenString = sym.name;
			 else tokenString = noString;
			}
			
		} else if (this.la.kind == 30) {
			this.Get();
			this.TokenExpr(tokenexprg);
			this.Expect(31);
			ret.g = tokenexpr.g; 
		} else if (this.la.kind == 32) {
			this.Get();
			this.TokenExpr(tokenexprg);
			this.Expect(33);
			ret.g = tokenexpr.g; this.tab.MakeOption(g); tokenString = noString; 
		} else if (this.la.kind == 34) {
			this.Get();
			this.TokenExpr(tokenexprg);
			this.Expect(35);
			ret.g = tokenexpr.g; this.tab.MakeIteration(g); tokenString = noString; 
		} else this.SynErr(51);
		if (ret.g == null) { // invalid start of TokenFactor
		ret.g = new Graph(this.tab.NewNode(Node.eps, null, 0)); 
		} 
	}


	public Parse() {
		this.la = new Token();
		this.la.val = "";		
		this.Get();
		this.Coco(null);
		this.Expect(0);

	}
	
	static stateset : bool[][] = [
		[true,true,false,true, false,true,false,false, false,false,true,true, false,false,false,true, true,true,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,true, false,false,false],
		[false,true,true,true, true,true,false,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,false],
		[false,true,true,true, true,true,true,false, false,false,false,false, true,true,true,false, false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,false],
		[true,true,false,true, false,true,false,false, false,false,true,true, false,false,false,true, true,true,true,false, false,false,false,true, false,false,false,false, true,true,true,false, true,false,true,false, true,true,false,true, false,false,false],
		[true,true,false,true, false,true,false,false, false,false,true,true, false,false,false,true, true,true,false,true, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,true, false,false,false],
		[true,true,false,true, false,true,false,false, false,false,true,true, false,false,false,true, true,true,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,true, false,false,false],
		[false,true,false,true, false,true,false,false, false,false,true,true, false,false,false,true, true,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,true, false,false,false],
		[false,true,false,true, false,true,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,true,false, true,false,true,false, false,false,false,false, false,false,false],
		[false,false,false,false, false,false,false,false, false,false,false,true, false,true,true,true, true,false,true,false, false,false,false,false, false,false,false,false, false,false,false,true, false,true,false,true, false,false,false,false, false,false,false],
		[false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,false,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,false],
		[false,true,true,true, false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,false,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,false],
		[false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,false, true,true,true,true, true,true,true,true, true,true,true,true, true,true,false],
		[false,true,true,true, false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,false, true,true,true,true, true,true,true,true, true,true,true,true, true,true,false],
		[false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, false,true,false],
		[false,true,true,true, false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,false, false,true,false],
		[false,true,false,true, false,true,false,false, false,false,false,false, false,false,false,false, false,false,true,false, false,false,false,true, false,false,false,false, true,true,true,true, true,true,true,true, true,true,false,true, false,false,false],
		[false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,true,false, false,false,false,false, false,false,false,false, false,false,false,true, false,true,false,true, false,false,false,false, false,false,false],
		[false,true,false,true, false,true,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,true, false,false,false,false, false,true,true,false, true,false,true,false, true,true,false,true, false,false,false],
		[false,true,false,true, false,true,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,true, false,false,false,false, false,true,true,false, true,false,true,false, true,false,false,true, false,false,false],
		[false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,true,false, false,false,false,false, false,false,false,false, true,false,false,true, false,true,false,true, false,false,false,false, false,false,false],
		[false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,false, true,true,true,true, true,true,true,true, true,true,false]

	];
} // end Parser

export interface ErrorStream
{
	WriteFormattedLine : (errorFormat : string, line : number, column : number, message : string) => void;
	WriteLine :  (message : string) => void;

}

export class Errors {
	public count : number = 0;                                    // number of errors detected

	public errorStream : ErrorStream;

	public errMsgFormat : string;

	Errors(_errorStream : ErrorStream, _errMsgFormat : string)
	{
		this.errorStream = _errorStream;
		this.errMsgFormat = _errMsgFormat;
	}

	public SynErrPositioned (line : number, col : number, n : number) {
		var s : string;
		switch (n) {
			case 0: s = "EOF expected"; break;
			case 1: s = "ident expected"; break;
			case 2: s = "number expected"; break;
			case 3: s = "string expected"; break;
			case 4: s = "badString expected"; break;
			case 5: s = "char expected"; break;
			case 6: s = "\"COMPILER\" expected"; break;
			case 7: s = "\"IGNORECASE\" expected"; break;
			case 8: s = "\"CHARACTERS\" expected"; break;
			case 9: s = "\"TOKENS\" expected"; break;
			case 10: s = "\"PRAGMAS\" expected"; break;
			case 11: s = "\"COMMENTS\" expected"; break;
			case 12: s = "\"FROM\" expected"; break;
			case 13: s = "\"TO\" expected"; break;
			case 14: s = "\"NESTED\" expected"; break;
			case 15: s = "\"IGNORE\" expected"; break;
			case 16: s = "\"PRODUCTIONS\" expected"; break;
			case 17: s = "\"=\" expected"; break;
			case 18: s = "\".\" expected"; break;
			case 19: s = "\"END\" expected"; break;
			case 20: s = "\"+\" expected"; break;
			case 21: s = "\"-\" expected"; break;
			case 22: s = "\"..\" expected"; break;
			case 23: s = "\"ANY\" expected"; break;
			case 24: s = "\"<\" expected"; break;
			case 25: s = "\">\" expected"; break;
			case 26: s = "\"<.\" expected"; break;
			case 27: s = "\".>\" expected"; break;
			case 28: s = "\"|\" expected"; break;
			case 29: s = "\"WEAK\" expected"; break;
			case 30: s = "\"(\" expected"; break;
			case 31: s = "\")\" expected"; break;
			case 32: s = "\"[\" expected"; break;
			case 33: s = "\"]\" expected"; break;
			case 34: s = "\"{\" expected"; break;
			case 35: s = "\"}\" expected"; break;
			case 36: s = "\"SYNC\" expected"; break;
			case 37: s = "\"IF\" expected"; break;
			case 38: s = "\"CONTEXT\" expected"; break;
			case 39: s = "\"(.\" expected"; break;
			case 40: s = "\".)\" expected"; break;
			case 41: s = "??? expected"; break;
			case 42: s = "this symbol not expected in Coco"; break;
			case 43: s = "this symbol not expected in TokenDecl"; break;
			case 44: s = "invalid TokenDecl"; break;
			case 45: s = "invalid AttrDecl"; break;
			case 46: s = "invalid SimSet"; break;
			case 47: s = "invalid Sym"; break;
			case 48: s = "invalid Term"; break;
			case 49: s = "invalid Factor"; break;
			case 50: s = "invalid Attribs"; break;
			case 51: s = "invalid TokenFactor"; break;

			default: s = "error " + n; break;
		}
		this.errorStream.WriteFormattedLine(this.errMsgFormat, line, col, s);
		this.count++;
	}

	public SemErrPositioned (line : number, col : number, s : string) {
		this.errorStream.WriteFormattedLine(this.errMsgFormat, line, col, s);
		this.count++;
	}
	
	public SemErr (s : string) {
		this.errorStream.WriteLine(s);
		this.count++;
	}
	
	public WarningPositioned (line : number, col : number, s : string) {
		this.errorStream.WriteFormattedLine(this.errMsgFormat, line, col, s);
	}
	
	public Warning(s : string) {
		this.errorStream.WriteLine(s);
	}
} // Errors
}