/*----------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2, or (at your option) any 
later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than 
Coco/R itself) does not fall under the GNU General Public License.
-----------------------------------------------------------------------*/


module at.jku.ssw.Coco {



/// <reference path="Scanner.ts" />
/// <reference path="Util.ts" />
/// <reference path="DFA.ts" />
/// <reference path="ParserGen.ts" />

export class Parser {
	public static _EOF : number = 0;
	public static _ident : number = 1;
	public static _number : number = 2;
	public static _string : number = 3;
	public static _badString : number = 4;
	public static _char : number = 5;
	public static maxT : number = 41;
	public static _ddtSym : number = 42;
	public static _optionSym : number = 43;

	static T : bool = true;
	static x : bool = false;
	static minErrDist : number = 2;
	
	public scanner : Scanner;
	public errors : Errors;

	public t : Token;    // last recognized token
	public la : Token;   // lookahead token
	public errDist = Parser.minErrDist;

get id() : number { return 0; }
	get str() : number { return 1; }
	
	public trace : TextWriter ;    // other Coco objects referenced in this ATG
	public tab : Tab;
	public dfa : DFA;
	public pgen : ParserGen;

	genScanner : bool;
	tokenString : string;         // used in declarations of literal tokens
	noString : string = "-none-"; // used in declarations of literal tokens

/*-------------------------------------------------------------------------*/



	constructor(scanner : Scanner) 
	{
		this.scanner = scanner;
		this.errors = new Errors();
	}

	SynErr (n : number)
	{
		if (this.errDist >= Parser.minErrDist)
		{
			this.errors.SynErrPositioned(this.la.line, this.la.col, n);
		}

		this.errDist = 0;
	}

	SemErr (msg : string)
	{
		if (this.errDist >= Parser.minErrDist)
		{
			this.errors.SemErrPositioned(this.t.line, this.t.col, msg);
		}

		this.errDist = 0;
	}
	
	Get ()
	{
		for (;;)
		{
			this.t = this.la;
			this.la = this.scanner.Scan();
			if (this.la.kind <= Parser.maxT) 
			{ 
				this.errDist++; 
				break; 
			}
				if (this.la.kind == 42) {
				tab.SetDDT(la.val); 
				}
				if (this.la.kind == 43) {
				tab.SetOption(la.val); 
				}

			this.la = this.t;
		}
	}
	
	Expect (n : number) {
		if (this.la.kind == n)
		{
			this.Get(); 
		}
		else
		{ 
			this.SynErr(n);
		}
	}
	
	StartOf (s : number) : bool {
		return Parser.stateset[s][this.la.kind];
	}
	
	ExpectWeak (n : number, follow : number) {
		if (this.la.kind == n) this.Get();
		else {
			this.SynErr(n);
			while (!this.StartOf(follow)) this.Get();
		}
	}


	WeakSeparator(n : number, syFol : number, repFol : number) : bool {
		var kind = this.la.kind;
		if (kind == n) {this.Get(); return true;}
		else if (this.StartOf(repFol)) {return false;}
		else {
			this.SynErr(n);
			while (!(Parser.stateset[syFol, kind] || Parser.stateset[repFol, kind] || Parser.stateset[0, kind])) {
				this.Get();
				kind = this.la.kind;
			}
			return this.StartOf(syFol);
		}
	}

	
	Coco()  : { } 
	 { 
		var ret : { };
		var sym : Symbol; var g : Graph; var g1 : Graph; var g2 : Graph; var gramName : string; var s : CharSet; var beg : number;var line : number; 
		if (this.StartOf(1)) {
			this.Get();
			beg = t.pos; line = t.line; 
			while (this.StartOf(1)) {
				this.Get();
			}
			pgen.usingPos = new Position(beg, la.pos, 0, line); 
		}
		this.Expect(6);
		genScanner = true; 
		tab.ignored = new CharSet(); 
		this.Expect(1);
		gramName = t.val;
		beg = la.pos; line = la.line;
		
		while (this.StartOf(2)) {
			this.Get();
		}
		tab.semDeclPos = new Position(beg, la.pos, 0, line); 
		if (this.la.kind == 7) {
			this.Get();
			dfa.ignoreCase = true; 
		}
		if (this.la.kind == 8) {
			this.Get();
			while (this.la.kind == 1) {
				var  = this.SetDecl();
			}
		}
		if (this.la.kind == 9) {
			this.Get();
			while (this.la.kind == 1 || this.la.kind == 3 || this.la.kind == 5) {
				var Node.t = this.TokenDecl();
			}
		}
		if (this.la.kind == 10) {
			this.Get();
			while (this.la.kind == 1 || this.la.kind == 3 || this.la.kind == 5) {
				var Node.pr = this.TokenDecl();
			}
		}
		while (this.la.kind == 11) {
			this.Get();
			var nested = false; 
			this.Expect(12);
			var tokenexprg1 = this.TokenExpr();
			g1 = tokenexprg1.g; 
			this.Expect(13);
			var tokenexprg2 = this.TokenExpr();
			g2 = tokenexprg2.g; 
			if (this.la.kind == 14) {
				this.Get();
				nested = true; 
			}
			dfa.NewComment(g1.l, g2.l, nested); 
		}
		while (this.la.kind == 15) {
			this.Get();
			var sets = this.Set();
			s = sets.s; tab.ignored.Or(s); 
		}
		while (!(this.la.kind == 0 || this.la.kind == 16)) {this.SynErr(42); Get();}
		this.Expect(16);
		if (genScanner) dfa.MakeDeterministic();
		tab.DeleteNodes();
		
		while (this.la.kind == 1) {
			this.Get();
			sym = tab.FindSym(t.val);
			var undef = sym == null;
			if (undef) sym = tab.NewSym(Node.nt, t.val, t.line);
			else {
			 if (sym.typ == Node.nt) {
			   if (sym.graph != null) SemErr("name declared twice");
			 } else { 
			   SemErr("this symbol kind not allowed on left side of production");
			 }
			 sym.line = t.line;
			}
			var noAttrs : bool = sym.attrPos == null;
			sym.attrPos = null;
			
			if (this.la.kind == 24 || this.la.kind == 26) {
				var sym = this.AttrDecl();
			}
			if (!undef) {
			 if (noAttrs != (sym.attrPos == null)) {
			   SemErr("attribute mismatch between declaration and use of this symbol");
			 }
			}
			
			if (this.la.kind == 39) {
				var out sym.semPos = this.SemText();
			}
			this.ExpectWeak(17, 3);
			var out g = this.Expression();
			sym.graph = g.l;
			tab.Finish(g);
			
			this.ExpectWeak(18, 4);
		}
		this.Expect(19);
		this.Expect(1);
		if (gramName != t.val) {
		 SemErr("name does not match grammar name");
		 tab.gramSy = tab.FindSym(gramName);
		}
		if (tab.gramSy == null) {
		 SemErr("missing production for grammar name");
		} else {
		 sym = tab.gramSy;
		 if (sym.attrPos != null) {
		   SemErr("grammar symbol must not have attributes");
		 }
		}
		tab.noSym = tab.NewSym(Node.t, "???", 0); // noSym gets highest number
		tab.SetupAnys();
		tab.RenumberPragmas();
		if (tab.ddt[2]) {
		  tab.PrintNodes();
		}
		if (errors.count == 0) {
		 Console.WriteLine("checking");
		 tab.CompSymbolSets();
		 if (tab.ddt[7]) { tab.XRef(); }
		 if (tab.GrammarOk()) {
		   Console.Write("parser");
		   pgen.WriteParser();
		   if (genScanner) {
		     Console.Write(" + scanner");
		     dfa.WriteScanner();
		     if (tab.ddt[0]) { dfa.PrintStates(); }
		   }
		   Console.WriteLine(" generated");
		   if (tab.ddt[8]) { pgen.WriteStatistics(); }
		 }
		}
		if (tab.ddt[6]) { tab.PrintSymbolTable(); }
		
		this.Expect(18);
		return ret;
	}
	SetDecl()  : { } 
	 { 
		var ret : { };
		var s : CharSet; 
		this.Expect(1);
		var name = t.val;
		var c = tab.FindCharClass(name);
		if (c != null) { SemErr("name declared twice"); }
		
		this.Expect(17);
		var s = this.Set();
		if (s.Elements() == 0) { SemErr("character set must not be empty"); }
		tab.NewCharClass(name, s);
		
		this.Expect(18);
		return ret;
	}
	TokenDecl()  : {typ : number } 
	 { 
		var ret : { typ : number};
		var name : string; var kind : number; var sym : Symbol; var g : Graph; 
		var name, kind = this.Sym();
		sym = tab.FindSym(name);
		if (sym != null) { SemErr("name declared twice"); }
		else {
		 sym = tab.NewSym(typ, name, t.line);
		 sym.tokenKind = Symbol.fixedToken;
		}
		tokenString = null;
		
		while (!(this.StartOf(5))) {this.SynErr(43); Get();}
		if (this.la.kind == 17) {
			this.Get();
			var g = this.TokenExpr();
			this.Expect(18);
			if (kind == str) { SemErr("a literal must not be declared with a structure"); }
			tab.Finish(g);
			if (tokenString == null || tokenString.Equals(noString)) {
			 dfa.ConvertToStates(g.l, sym);
			} else { // TokenExpr is a single string
			 if (tab.literals[tokenString] != null) {
			   SemErr("token string declared twice");
			 }
			 tab.literals[tokenString] = sym;
			 dfa.MatchLiteral(tokenString, sym);
			}
			
		} else if (this.StartOf(6)) {
			if (kind == id) { genScanner = false; }
			else { dfa.MatchLiteral(sym.name, sym); }
			
		} else this.SynErr(44);
		if (this.la.kind == 39) {
			var out sym.semPos = this.SemText();
			if (typ != Node.pr) { SemErr("semantic action not allowed here"); } 
		}
		return ret;
	}
	TokenExpr()  : {g : Graph; } 
	 { 
		var ret : { g : Graph;};
		var g2 : Graph; 
		var tokentermg = this.TokenTerm();
		ret.g = tokentermg.g; var first = true; 
		while (this.WeakSeparator(28,7,8) ) {
			var tokentermg2 = this.TokenTerm();
			g2 = tokentermg2.g;
			if (first) { tab.MakeFirstAlt(ret.g); first = false; }
			tab.MakeAlternative(ret.g, g2);
			
		}
		return ret;
	}
	Set()  : {s : CharSet; } 
	 { 
		var ret : { s : CharSet;};
		var s2 : CharSet; 
		var ret.s = this.SimSet();
		while (this.la.kind == 20 || this.la.kind == 21) {
			if (this.la.kind == 20) {
				this.Get();
				var s2 = this.SimSet();
				ret.s.Or(s2); 
			} else {
				this.Get();
				var s2 = this.SimSet();
				ret.s.Subtract(s2); 
			}
		}
		return ret;
	}
	AttrDecl()  : {sym : Symbol; } 
	 { 
		var ret : { sym : Symbol;};
		if (this.la.kind == 24) {
			this.Get();
			var beg = la.pos; var col = la.col; var line = la.line; 
			while (this.StartOf(9)) {
				if (this.StartOf(10)) {
					this.Get();
				} else {
					this.Get();
					SemErr("bad string in attributes"); 
				}
			}
			this.Expect(25);
			if (t.pos > beg) {
			 sym.attrPos = new Position(beg, t.pos, col, line); 
			} 
			
		} else if (this.la.kind == 26) {
			this.Get();
			var beg = la.pos; var col = la.col; var line = la.line; 
			while (this.StartOf(11)) {
				if (this.StartOf(12)) {
					this.Get();
				} else {
					this.Get();
					SemErr("bad string in attributes"); 
				}
			}
			this.Expect(27);
			if (t.pos > beg) {
			 sym.attrPos = new Position(beg, t.pos, col, line); 
			} 
			
		} else this.SynErr(45);
		return ret;
	}
	SemText()  : {pos : Position; } 
	 { 
		var ret : { pos : Position;};
		this.Expect(39);
		var beg = la.pos; var col = la.col; var line = la.line; 
		while (this.StartOf(13)) {
			if (this.StartOf(14)) {
				this.Get();
			} else if (this.la.kind == 4) {
				this.Get();
				SemErr("bad string in semantic action"); 
			} else {
				this.Get();
				SemErr("missing end of previous semantic action"); 
			}
		}
		this.Expect(40);
		ret.pos = new Position(beg, t.pos, col, line); 
		return ret;
	}
	Expression()  : {g : Graph; } 
	 { 
		var ret : { g : Graph;};
		var term1 = this.Term();
		ret.g = term1.g; var first = true; 
		while (this.WeakSeparator(28,15,16) ) {
			var term2 = this.Term();
			if (first) { tab.MakeFirstAlt(ret.g); first = false; }
			tab.MakeAlternative(ret.g, term2.g);
			
		}
		return ret;
	}
	SimSet()  : {s : CharSet; } 
	 { 
		var ret : { s : CharSet;};
		var n1 : number; var n2 : number; 
		s = new CharSet(); 
		if (this.la.kind == 1) {
			this.Get();
			var c = tab.FindCharClass(t.val);
			if (c == null) { SemErr("undefined name"); } else { s.Or(c.set); }
			
		} else if (this.la.kind == 3) {
			this.Get();
			var name = t.val;
			name = tab.Unescape(name.Substring(1, name.Length-2));
			foreach (char ch in name) {
			 if (dfa.ignoreCase) { s.Set(char.ToLower(ch)); }
			 else { s.Set(ch); }
			}  
		} else if (this.la.kind == 5) {
			var n1 : number; = this.Char();
			s.Set(n1); 
			if (this.la.kind == 22) {
				this.Get();
				var n2 = this.Char();
				for (var i = n1; i <= n2; i++) { s.Set(i); } 
			}
		} else if (this.la.kind == 23) {
			this.Get();
			s = new CharSet(); s.Fill(); 
		} else this.SynErr(46);
		return ret;
	}
	Char()  : {n : string; } 
	 { 
		var ret : { n : string;};
		this.Expect(5);
		var name = t.val; n = '\0';
		name = tab.Unescape(name.Substring(1, name.Length-2));
		if (name.Length == 1) { n = name[0]; }
		else { SemErr("unacceptable character value"); }
		if (dfa.ignoreCase && n >= 'A' && n <= 'Z') n = n.toUpper();
		
		return ret;
	}
	Sym()  : {name : string; kind : number; } 
	 { 
		var ret : { name : string; kind : number;};
		ret.name = "???"; ret.kind = id; 
		if (this.la.kind == 1) {
			this.Get();
			ret.kind = id; ret.name = t.val; 
		} else if (this.la.kind == 3 || this.la.kind == 5) {
			if (this.la.kind == 3) {
				this.Get();
				ret.name = t.val; 
			} else {
				this.Get();
				ret.name = "\"" + t.val.Substring(1, t.val.Length-2) + "\""; 
			}
			ret.kind = str;
			if (dfa.ignoreCase) ret.name = ret.name.ToLower();
			if (ret.name.IndexOf(' ') >= 0)
			 SemErr("literal tokens must not contain blanks"); 
		} else this.SynErr(47);
		return ret;
	}
	Term()  : {g : Graph; } 
	 { 
		var ret : { g : Graph;};
		var g2 : Graph; var rslv : Node = null; g = null; 
		if (this.StartOf(17)) {
			if (this.la.kind == 37) {
				rslv = tab.NewNode(Node.rslv, null, la.line); 
				var rslvpos = this.Resolver();
				rslv.pos = rslvpos.pos; g = new Graph(rslv); 
			}
			var factorg2 = this.Factor();
			g2 = factorg2.g;
			if (rslv != null) tab.MakeSequence(ret.g, ret.g2);
			else ret.g = g2;
			
			while (this.StartOf(18)) {
				var factorg2 = this.Factor();
				g2 = factorg2.g; tab.MakeSequence(ret.g, ret.g2); 
			}
		} else if (this.StartOf(19)) {
			g = new Graph(tab.NewNode(Node.eps, null, 0)); 
		} else this.SynErr(48);
		if (g == null) { // invalid start of Term
		 g = new Graph(tab.NewNode(Node.eps, null, 0));
		}
		
		return ret;
	}
	Resolver()  : {pos : Position; } 
	 { 
		var ret : { pos : Position;};
		this.Expect(37);
		this.Expect(30);
		var beg = la.pos; var col = la.col; var line = la.line; 
		var  = this.Condition();
		ret.pos = new Position(beg, t.pos, col, line); 
		return ret;
	}
	Factor()  : {out Graph g } 
	 { 
		var ret : { out Graph g};
		var name : string; var kind : number; var pos : Position; var weak : bool = false; 
		g = null;
		
		switch (this.la.kind) {
		case 1: case 3: case 5: case 29: {
			if (this.la.kind == 29) {
				this.Get();
				weak = true; 
			}
			var out name, out kind = this.Sym();
			var sym = tab.FindSym(name);
			if (sym == null && kind == str)
			 sym = tab.literals[name] as Symbol;
			var undef = sym == null;
			if (undef) {
			 if (kind == id) {
			   sym = tab.NewSym(Node.nt, name, 0);  // forward nt
			 } else if (genScanner) { 
			   sym = tab.NewSym(Node.t, name, t.line);
			   dfa.MatchLiteral(sym.name, sym);
			 } else {  // undefined string in production
			   SemErr("undefined string in production");
			   sym = tab.eofSy;  // dummy
			 }
			}
			var typ = sym.typ;
			if (typ != Node.t && typ != Node.nt) {
			 SemErr("this symbol kind is not allowed in a production");
			}
			if (weak) {
			 if (typ == Node.t) { typ = Node.wt; }
			 else { SemErr("only terminals may be weak"); }
			}
			var p = tab.NewNode(typ, sym, t.line);
			g = new Graph(p);
			
			if (this.la.kind == 24 || this.la.kind == 26) {
				var p = this.Attribs();
				if (kind != id) { SemErr("a literal must not have attributes"); } 
			}
			if (undef) {
			 sym.attrPos = p.pos;  // dummy
			} else if ((p.pos == null) != (sym.attrPos == null)) {
			 SemErr("attribute mismatch between declaration and use of this symbol");
			}
			
			break;
		}
		case 30: {
			this.Get();
			var out g = this.Expression();
			this.Expect(31);
			break;
		}
		case 32: {
			this.Get();
			var out g = this.Expression();
			this.Expect(33);
			tab.MakeOption(g); 
			break;
		}
		case 34: {
			this.Get();
			var out g = this.Expression();
			this.Expect(35);
			tab.MakeIteration(g); 
			break;
		}
		case 39: {
			var out pos = this.SemText();
			Node p = tab.NewNode(Node.sem, null, 0);
			p.pos = pos;
			g = new Graph(p);
			
			break;
		}
		case 23: {
			this.Get();
			var p = tab.NewNode(Node.any, null, 0);  // p.set is set in tab.SetupAnys
			g = new Graph(p);
			
			break;
		}
		case 36: {
			this.Get();
			var p = tab.NewNode(Node.sync, null, 0);
			g = new Graph(p);
			
			break;
		}
		default: this.SynErr(49); break;
		}
		if (g == null) {// invalid start of Factor
		 g = new Graph(tab.NewNode(Node.eps, null, 0));
		}
		return ret;
	}
	Attribs()  : {p : Node } 
	 { 
		var ret : { p : Node};
		if (this.la.kind == 24) {
			this.Get();
			var beg = la.pos; var col = la.col; var line = la.line; 
			while (this.StartOf(9)) {
				if (this.StartOf(10)) {
					this.Get();
				} else {
					this.Get();
					SemErr("bad string in attributes"); 
				}
			}
			this.Expect(25);
			if (t.pos > beg) p.pos = new Position(beg, t.pos, col, line); 
		} else if (this.la.kind == 26) {
			this.Get();
			var beg = la.pos; var col = la.col; var line = la.line; 
			while (this.StartOf(11)) {
				if (this.StartOf(12)) {
					this.Get();
				} else {
					this.Get();
					SemErr("bad string in attributes"); 
				}
			}
			this.Expect(27);
			if (t.pos > beg) p.pos = new Position(beg, t.pos, col, line); 
		} else this.SynErr(50);
		return ret;
	}
	Condition()  : { } 
	 { 
		var ret : { };
		while (this.StartOf(20)) {
			if (this.la.kind == 30) {
				this.Get();
				var  = this.Condition();
			} else {
				this.Get();
			}
		}
		this.Expect(31);
		return ret;
	}
	TokenTerm()  : {g: Graph; } 
	 { 
		var ret : { g: Graph;};
		var g2 : Graph; 
		var tokenfactorg = this.TokenFactor();
		g = tokenfactorg.g; 
		while (this.StartOf(7)) {
			var tokenfactorg2 = this.TokenFactor();
			g2 = tokenfactorg2.g; 
			tab.MakeSequence(g, g2); 
		}
		if (this.la.kind == 38) {
			this.Get();
			this.Expect(30);
			var tokenexprg2 = this.TokenExpr();
			g2 = tokenexprg2.g; 
			tab.SetContextTrans(g2.l); dfa.hasCtxMoves = true;
			tab.MakeSequence(g, g2); 
			this.Expect(31);
		}
		return ret;
	}
	TokenFactor()  : {g : Graph; } 
	 { 
		var ret : { g : Graph;};
		
		ret.g = null; 
		if (this.la.kind == 1 || this.la.kind == 3 || this.la.kind == 5) {
			var sym = this.Sym();
			if (sym.kind == id) {
			 var c = tab.FindCharClass(sym.name);
			 if (c == null) {
			   SemErr("undefined name");
			   c = tab.NewCharClass(sym.name, new CharSet());
			 }
			 var p = tab.NewNode(Node.clas, null, 0); 
			 p.val = c.n;
			 ret.g = new Graph(p);
			 tokenString = noString;
			} else { // str
			 ret.g = tab.StrToGraph(sym.name);
			 if (tokenString == null) tokenString = sym.name;
			 else tokenString = noString;
			}
			
		} else if (this.la.kind == 30) {
			this.Get();
			var tokenexprg = this.TokenExpr();
			this.Expect(31);
			ret.g = tokenexpr.g; 
		} else if (this.la.kind == 32) {
			this.Get();
			var tokenexprg = this.TokenExpr();
			this.Expect(33);
			ret.g = tokenexpr.g; tab.MakeOption(g); tokenString = noString; 
		} else if (this.la.kind == 34) {
			this.Get();
			var tokenexprg = this.TokenExpr();
			this.Expect(35);
			ret.g = tokenexpr.g; tab.MakeIteration(g); tokenString = noString; 
		} else this.SynErr(51);
		if (ret.g == null) { // invalid start of TokenFactor
		ret.g = new Graph(tab.NewNode(Node.eps, null, 0)); 
		} 
		return ret;
	}


	public Parse() {
		this.la = new Token();
		this.la.val = "";		
		this.Get();
		this.Coco();
		this.Expect(0);

	}
	
	static stateset : bool[][] = [
		[true,true,false,true, false,true,false,false, false,false,true,true, false,false,false,true, true,true,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,true, false,false,false],
		[false,true,true,true, true,true,false,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,false],
		[false,true,true,true, true,true,true,false, false,false,false,false, true,true,true,false, false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,false],
		[true,true,false,true, false,true,false,false, false,false,true,true, false,false,false,true, true,true,true,false, false,false,false,true, false,false,false,false, true,true,true,false, true,false,true,false, true,true,false,true, false,false,false],
		[true,true,false,true, false,true,false,false, false,false,true,true, false,false,false,true, true,true,false,true, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,true, false,false,false],
		[true,true,false,true, false,true,false,false, false,false,true,true, false,false,false,true, true,true,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,true, false,false,false],
		[false,true,false,true, false,true,false,false, false,false,true,true, false,false,false,true, true,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,true, false,false,false],
		[false,true,false,true, false,true,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,true,false, true,false,true,false, false,false,false,false, false,false,false],
		[false,false,false,false, false,false,false,false, false,false,false,true, false,true,true,true, true,false,true,false, false,false,false,false, false,false,false,false, false,false,false,true, false,true,false,true, false,false,false,false, false,false,false],
		[false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,false,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,false],
		[false,true,true,true, false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,false,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,false],
		[false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,false, true,true,true,true, true,true,true,true, true,true,true,true, true,true,false],
		[false,true,true,true, false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,false, true,true,true,true, true,true,true,true, true,true,true,true, true,true,false],
		[false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, false,true,false],
		[false,true,true,true, false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,false, false,true,false],
		[false,true,false,true, false,true,false,false, false,false,false,false, false,false,false,false, false,false,true,false, false,false,false,true, false,false,false,false, true,true,true,true, true,true,true,true, true,true,false,true, false,false,false],
		[false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,true,false, false,false,false,false, false,false,false,false, false,false,false,true, false,true,false,true, false,false,false,false, false,false,false],
		[false,true,false,true, false,true,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,true, false,false,false,false, false,true,true,false, true,false,true,false, true,true,false,true, false,false,false],
		[false,true,false,true, false,true,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,true, false,false,false,false, false,true,true,false, true,false,true,false, true,false,false,true, false,false,false],
		[false,false,false,false, false,false,false,false, false,false,false,false, false,false,false,false, false,false,true,false, false,false,false,false, false,false,false,false, true,false,false,true, false,true,false,true, false,false,false,false, false,false,false],
		[false,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,true, true,true,true,false, true,true,true,true, true,true,true,true, true,true,false]

	];
} // end Parser

export interface ErrorStream
{
	WriteFormattedLine : (errorFormat : string, line : number, column : number, message : string) => void;
	WriteLine :  (message : string) => void;

}

export class Errors {
	public count : number = 0;                                    // number of errors detected

	public errorStream : ErrorStream;

	public errMsgFormat : string;

	Errors(_errorStream : ErrorStream, _errMsgFormat : string)
	{
		this.errorStream = _errorStream;
		this.errMsgFormat = _errMsgFormat;
	}

	public SynErrPositioned (line : number, col : number, n : number) {
		var s : string;
		switch (n) {
			case 0: s = "EOF expected"; break;
			case 1: s = "ident expected"; break;
			case 2: s = "number expected"; break;
			case 3: s = "string expected"; break;
			case 4: s = "badString expected"; break;
			case 5: s = "char expected"; break;
			case 6: s = "\"COMPILER\" expected"; break;
			case 7: s = "\"IGNORECASE\" expected"; break;
			case 8: s = "\"CHARACTERS\" expected"; break;
			case 9: s = "\"TOKENS\" expected"; break;
			case 10: s = "\"PRAGMAS\" expected"; break;
			case 11: s = "\"COMMENTS\" expected"; break;
			case 12: s = "\"FROM\" expected"; break;
			case 13: s = "\"TO\" expected"; break;
			case 14: s = "\"NESTED\" expected"; break;
			case 15: s = "\"IGNORE\" expected"; break;
			case 16: s = "\"PRODUCTIONS\" expected"; break;
			case 17: s = "\"=\" expected"; break;
			case 18: s = "\".\" expected"; break;
			case 19: s = "\"END\" expected"; break;
			case 20: s = "\"+\" expected"; break;
			case 21: s = "\"-\" expected"; break;
			case 22: s = "\"..\" expected"; break;
			case 23: s = "\"ANY\" expected"; break;
			case 24: s = "\"<\" expected"; break;
			case 25: s = "\">\" expected"; break;
			case 26: s = "\"<.\" expected"; break;
			case 27: s = "\".>\" expected"; break;
			case 28: s = "\"|\" expected"; break;
			case 29: s = "\"WEAK\" expected"; break;
			case 30: s = "\"(\" expected"; break;
			case 31: s = "\")\" expected"; break;
			case 32: s = "\"[\" expected"; break;
			case 33: s = "\"]\" expected"; break;
			case 34: s = "\"{\" expected"; break;
			case 35: s = "\"}\" expected"; break;
			case 36: s = "\"SYNC\" expected"; break;
			case 37: s = "\"IF\" expected"; break;
			case 38: s = "\"CONTEXT\" expected"; break;
			case 39: s = "\"(.\" expected"; break;
			case 40: s = "\".)\" expected"; break;
			case 41: s = "??? expected"; break;
			case 42: s = "this symbol not expected in Coco"; break;
			case 43: s = "this symbol not expected in TokenDecl"; break;
			case 44: s = "invalid TokenDecl"; break;
			case 45: s = "invalid AttrDecl"; break;
			case 46: s = "invalid SimSet"; break;
			case 47: s = "invalid Sym"; break;
			case 48: s = "invalid Term"; break;
			case 49: s = "invalid Factor"; break;
			case 50: s = "invalid Attribs"; break;
			case 51: s = "invalid TokenFactor"; break;

			default: s = "error " + n; break;
		}
		this.errorStream.WriteFormattedLine(this.errMsgFormat, line, col, s);
		this.count++;
	}

	public SemErrPositioned (line : number, col : number, s : string) {
		this.errorStream.WriteFormattedLine(this.errMsgFormat, line, col, s);
		this.count++;
	}
	
	public SemErr (s : string) {
		this.errorStream.WriteLine(s);
		this.count++;
	}
	
	public WarningPositioned (line : number, col : number, s : string) {
		this.errorStream.WriteFormattedLine(this.errMsgFormat, line, col, s);
	}
	
	public Warning(s : string) {
		this.errorStream.WriteLine(s);
	}
} // Errors
}