/*----------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2, or (at your option) any 
later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than 
Coco/R itself) does not fall under the GNU General Public License.
-----------------------------------------------------------------------*/


module test {



/// <reference path="Scanner.ts" />

export class Parser {
	public static _EOF : number = 0;
	public static _ident : number = 1;
	public static _number : number = 2;
	public static maxT : number = 12;

	static T : bool = true;
	static x : bool = false;
	static minErrDist : number = 2;
	
	public scanner : Scanner;
	public errors : Errors;

	public t : Token;    // last recognized token
	public la : Token;   // lookahead token
	public errDist = Parser.minErrDist;



	public Parser(scanner : Scanner) 
	{
		this.scanner = scanner;
		this.errors = new Errors();
	}

	SynErr (n : number)
	{
		if (this.errDist >= Parser.minErrDist)
		{
			this.errors.SynErr(this.la.line, this.la.col, n);
		}

		this.errDist = 0;
	}

	SemErr (msg : string)
	{
		if (this.errDist >= Parser.minErrDist)
		{
			this.errors.SemErr(this.t.line, this.t.col, msg);
		}

		this.errDist = 0;
	}
	
	Get ()
	{
		for (;;)
		{
			this.t = this.la;
			this.la = this.scanner.Scan();
			if (this.la.kind <= Parser.maxT) 
			{ 
				this.errDist++; 
				break; 
			}

			this.la = this.t;
		}
	}
	
	Expect (n : number) {
		if (this.la.kind == n)
		{
			this.Get(); 
		}
		else
		{ 
			this.SynErr(n);
		}
	}
	
	StartOf (s : number) : bool {
		return Parser.stateset[s][this.la.kind];
	}
	
	ExpectWeak (n : number, follow : number) {
		if (this.la.kind == n) this.Get();
		else {
			this.SynErr(n);
			while (!this.StartOf(follow)) this.Get();
		}
	}


	WeakSeparator(n : number, syFol : number, repFol : number) : bool {
		var kind = this.la.kind;
		if (kind == n) {this.Get(); return true;}
		else if (this.StartOf(repFol)) {return false;}
		else {
			this.SynErr(n);
			while (!(Parser.stateset[syFol, kind] || Parser.stateset[repFol, kind] || Parser.stateset[0, kind])) {
				this.Get();
				kind = this.la.kind;
			}
			return this.StartOf(syFol);
		}
	}

	
	AddOp() {
		if (this.la.kind == 3) {
			this.Get();
		} else if (this.la.kind == 4) {
			this.Get();
		} else this.SynErr(13);
	}

	MulOp() {
		if (this.la.kind == 5) {
			this.Get();
		} else if (this.la.kind == 6) {
			this.Get();
		} else this.SynErr(14);
	}

	RelOp() {
		if (this.la.kind == 7) {
			this.Get();
		} else if (this.la.kind == 8) {
			this.Get();
		} else if (this.la.kind == 9) {
			this.Get();
		} else this.SynErr(15);
	}

	Expr() {
		this.SimExpr();
		if (this.la.kind == 7 || this.la.kind == 8 || this.la.kind == 9) {
			this.RelOp();
			this.SimExpr();
		}
	}

	SimExpr() {
		this.Term();
		while (this.la.kind == 3 || this.la.kind == 4) {
			this.AddOp();
			this.Term();
		}
	}

	Factor() {
		if (this.la.kind == 1) {
			this.Ident();
		} else if (this.la.kind == 2) {
			this.Get();
		} else if (this.la.kind == 4) {
			this.Get();
			this.Factor();
		} else if (this.la.kind == 10) {
			this.Get();
		} else if (this.la.kind == 11) {
			this.Get();
		} else this.SynErr(16);
	}

	Ident() {
		this.Expect(1);
	}

	Term() {
		this.Factor();
		while (this.la.kind == 5 || this.la.kind == 6) {
			this.MulOp();
			this.Factor();
		}
	}

	Test() {
		this.Expr();
	}



	public Parse() {
		this.la = new Token();
		this.la.val = "";		
		this.Get();
		this.Test();
		this.Expect(0);

	}
	
	static stateset : bool[][] = [
		[true,false,false,false, false,false,false,false, false,false,false,false, false,false]

	];
} // end Parser


public class Errors {
	public count : number = 0;                                    // number of errors detected

	public SynErr (line : number, col : number, n : number) {
		var s : string;
		switch (n) {
			case 0: s = "EOF expected"; break;
			case 1: s = "ident expected"; break;
			case 2: s = "number expected"; break;
			case 3: s = "\"+\" expected"; break;
			case 4: s = "\"-\" expected"; break;
			case 5: s = "\"*\" expected"; break;
			case 6: s = "\"/\" expected"; break;
			case 7: s = "\"==\" expected"; break;
			case 8: s = "\"<\" expected"; break;
			case 9: s = "\">\" expected"; break;
			case 10: s = "\"true\" expected"; break;
			case 11: s = "\"false\" expected"; break;
			case 12: s = "??? expected"; break;
			case 13: s = "invalid AddOp"; break;
			case 14: s = "invalid MulOp"; break;
			case 15: s = "invalid RelOp"; break;
			case 16: s = "invalid Factor"; break;

			default: s = "error " + n; break;
		}
		// TODO: write error errorStream.WriteLine(errMsgFormat, line, col, s);
		this.count++;
	}

	public virtual SemErr (line : number, col : number, s : string) {
		errorStream.WriteLine(errMsgFormat, line, col, s);
		this.count++;
	}
	
	public SemErr (s : string) {
		errorStream.WriteLine(s);
		this.count++;
	}
	
	public Warning (line : number, col : number, s : string) {
		errorStream.WriteLine(errMsgFormat, line, col, s);
	}
	
	public Warning(s : string) {
		errorStream.WriteLine(s);
	}
} // Errors


public class FatalError: Exception {
	public FatalError(string m): base(m) {}
}
}